version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    on-failure: CONTINUE
    commands:
      - aws ecr create-repository -repository-name dibs-fe-paraphrase --image-scanning-configuration scanOnPush=true --region us-east-1
    finally:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - aws ecr batch-delete-image --repository-name dibs-fe-paraphrase --image-ids imageTag=latest-paraphrase
      - docker build -t dibs-fe-paraphrase:latest-paraphrase .
      - docker tag dibs-fe-paraphrase:latest-paraphrase $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dibs-fe-paraphrase:latest-paraphrase
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/dibs-fe-paraphrase:latest-paraphrase
  build:
    commands:
      - aws cloudformation deploy --template-file template.yml --stack-name dibs-fe-paraphrase --parameter-overrides stage=$STAGE --capabilities CAPABILITY_IAM --region us-east-1
