AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  Paraphrase Model on Lambda

Resources:
  ParaphraseEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 5000
      Timeout: 900
      Events:
        ParaphraseCodeBuildApi:
          Type: Api
          Properties:
            Path: /codeBuild-paraphrase
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.8-v1
